import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    "Features": "Features",
    "Solutions": "Solutions",
    "Documentation": "Documentation",
    "Sign up": "Sign up",
    "Industrial 4.0 Standard": "Industrial 4.0 Standard",
    "Visualize and Optimize": "Visualize and Optimize",
    "Your": "Your",
    "Network": "Network",
    "Real-time monitoring and advanced diagnostics for industrial-scale LoRa networks.": "Real-time monitoring and advanced diagnostics for industrial-scale LoRa networks.",
    "Start Monitoring": "Start Monitoring",
    "Watch Demo": "Watch Demo",
    "Infinite Scalability": "Infinite Scalability",
    "Support for thousands of nodes across vast areas without degradation.": "Support for thousands of nodes across vast areas without degradation.",
    "Real-time Data": "Real-time Data",
    "Instant latency tracking and packet delivery metrics with sub-second updates.": "Instant latency tracking and packet delivery metrics with sub-second updates.",
    "Historical Analysis": "Historical Analysis",
    "Deep trend analysis to predict failures before they occur.": "Deep trend analysis to predict failures before they occur.",
    "Ready to optimize your network?": "Ready to optimize your network?",
    "Enter your work email to receive a customized implementation plan.": "Enter your work email to receive a customized implementation plan.",
    "Enter your work email": "Enter your work email",
    "Get Consulted": "Get Consulted",
    "Privacy Policy": "Privacy Policy",
    "Terms of Service": "Terms of Service",
    "API Keys": "API Keys",
    "Change language": "Change language",
    "Change theme": "Change theme",
    "LogoutLabel": "Logout",
    "Welcome Back": "Welcome Back",
    "Access your mesh network dashboard": "Access your mesh network dashboard",
    "Usuario": "Username",
    "Contrasena": "Password",
    "Sign In": "Sign In",
    "Ingresando...": "Signing in...",
    "Credenciales invalidas": "Invalid credentials",
    "Error al conectar con la API": "Error connecting to the API",
    "Industrial Mesh Control": "Industrial Mesh Control",
    "Real-time monitoring and deployment of LoRa-based sensor nodes.": "Real-time monitoring and deployment of LoRa-based sensor nodes.",
    "Active Network Nodes": "Active Network Nodes",
    "Provision New Node": "Provision New Node",
    "Edit Node Configuration": "Edit Node Configuration",
    "Node Model": "Node Model",
    "Refresh Rate (seconds)": "Refresh Rate (seconds)",
    "Deploy Node to Mesh": "Deploy Node to Mesh",
    "Save Changes": "Save Changes",
    "Cancel": "Cancel",
    "Editar": "Edit",
    "Eliminar": "Delete",
    "Desactivar": "Deactivate",
    "Activar": "Activate",
    "Confirmar Eliminación": "Confirm Deletion",
    "Sí, Eliminar": "Yes, Delete",
    "Live Node Grid": "Live Node Grid",
    "Real-time telemetry from mesh nodes": "Real-time telemetry from mesh nodes",
    "New Node": "New Node",
    "Offline": "Offline",
    "Active": "Active",
    "nodos": "nodes",
    "Refresh": "Refresh",
    "Status": "Status",
    "Actions": "Actions",
    "Creando...": "Creating...",
    "Guardando...": "Saving...",
    "No hay nodos disponibles.": "No nodes available.",
    "Cargando nodos...": "Loading nodes...",
    "Error al cargar los datos": "Error loading data",
    "Inicio": "Home",
    "Dashboard": "Dashboard",
    "Panel de nodos": "Nodes Panel",
    "Informacion general de nodos": "General node information",
    "Gestor de nodos": "Node Manager",
    "Panel de Nodos": "Nodes Panel",
    "Mapa en Vivo": "Live Map",
    "Históricos": "Historical",
    "Log de Paquetes": "Packet Log",
    "Buscar nodos, IPs...": "Search nodes, IPs...",
    "Configuración": "Settings",
    "Cerrar Sesión": "Logout",
    "Nosotros": "About Us",
    "Descargas": "Downloads",
    "Proyecto": "Project",
    "Ver panel": "View Panel",
    "Ingresar": "Sign In",
    "Ir al sistema": "Enter System",
    "Nuestra Misión": "Our Mission",
    "Equipo de Desarrollo": "Development Team",
    "Desarrolladores del proyecto Final de Ingeniería Electrónica": "Electronic Engineering Final Project Developers",
    "Firmware Nodos": "Nodes Firmware",
    "Gateway LoRa": "LoRa Gateway",
    "Guía de Instalación": "Installation Guide",
    "Recursos del Proyecto": "Project Resources",
    "Repositorios oficiales y guías de configuración.": "Official repositories and configuration guides.",
    "Bajo Consumo": "Low Consumption",
    "Optimizado para funcionar meses con baterias.": "Optimized to run for months on batteries.",
    "Largo Alcance": "Long Range",
    "Comunicación de hasta 10km en línea de vista.": "Communication up to 10km in line of sight.",
    "Seguridad": "Security",
    "Cifrado AES-128 de extremo a extremo": "End-to-end AES-128 encryption",
    "Red de sensores inalámbricos": "Wireless sensor network",
    "Sistema autónomo de monitoreo ambiental": "Autonomous environmental monitoring system",
    "Resumen tecnico": "Technical Summary",
    "¿Qué es LoRa Mesh?": "What is LoRa Mesh?",
    "Es una arquitectura de red donde los nodos cooperan": "It is a network architecture where nodes cooperate",
    "Empoderando la telemetría industrial": "Empowering industrial telemetry",
    "Soluciones robustas para ambientes desafiantes.": "Robust solutions for challenging environments.",
    "Contacto": "Contact",
    "Soporte": "Support",
    "Red de sensores inalámbricos": "Wireless sensor network",
    "Descargas y Recursos": "Downloads & Resources",
    "Accede a los repositorios y guías de instalación del ecosistema LoRa Mesh.": "Access the repositories and installation guides of the LoRa Mesh ecosystem.",
    "Ir al Repositorio": "Go to Repository",
    "Leer Guía": "Read Guide",
    "Código fuente para los nodos LoRa Mesh basados en microcontroladores ESP32/Arduino.": "Source code for LoRa Mesh nodes based on ESP32/Arduino microcontrollers.",
    "Software para el nodo concentrador encargado de la recepción y envío de datos a la nube.": "Software for the hub node in charge of receiving and sending data to the cloud.",
    "Documentación paso a paso para desplegar tu propia red de monitoreo.": "Step-by-step documentation to deploy your own monitoring network.",
    "Desarrollador y diseñador del sistema de telemetría LoRa Mesh. Enfocado en el hardware y la arquitectura de la red.": "Developer and designer of the LoRa Mesh telemetry system. Focused on hardware and network architecture.",
    "Especialista en desarrollo web y despliegue del software. Encargado de la visualización y análisis de datos en tiempo real.": "Web development and software deployment specialist. In charge of real-time data visualization and analysis.",
    "Integrante 1": "Member 1",
    "Integrante 2": "Member 2",
    "Documentación técnica detallada para el despliegue de la red y configuración del software.": "Detailed technical documentation for network deployment and software configuration.",
    "Proyecto Final - Ingenieria Electronica": "Final Project - Electronic Engineering",
    "Monitoreo distribuido": "Distributed monitoring",
    "en": "in",
    "Plataforma orientada a zonas remotas que combina bajo consumo, alcance extendido y comunicacion multisalto para transportar lecturas ambientales hacia un nodo concentrador.": "Remote area platform combining low power, extended range and multi-hop communication to transport environmental readings to a collector node.",
    "Objetivo general": "General Objective",
    "Objetivo tecnico": "Technical Objective",
    "Objetivo de impacto": "Impact Objective",
    "Implementar una red LoRa Mesh funcional para monitoreo en entornos sin infraestructura tradicional.": "Implement a functional LoRa Mesh network for monitoring in environments without traditional infrastructure.",
    "Validar comunicaciones multisalto entre nodos y concentrar datos en gateway para visualizacion web.": "Validate multi-hop communications between nodes and concentrate data in a gateway for web visualization.",
    "Ofrecer una alternativa replicable, de bajo costo operativo and adaptable a distintos escenarios.": "Offer a replicable alternative, with low operating cost and adaptable to different scenarios.",
    "Nodos distribuidos": "Distributed Nodes",
    "Comunicacion Mesh": "Mesh Communication",
    "Gateway + plataforma": "Gateway + Platform",
    "Captura de variables ambientales en diferentes puntos de campo.": "Capture of environmental variables in different field points.",
    "Los datos se enrutan por saltos intermedios para extender cobertura y mejorar resiliencia.": "Data is routed via intermediate hops to extend coverage and improve resilience.",
    "Centralizacion de datos y visualizacion historica en una interfaz web simple.": "Data centralization and historical visualization in a simple web interface.",
    "Aplicaciones potenciales": "Potential Applications",
    "Agricultura de precision, monitoreo ambiental, energias renovables e iniciativas academicas que requieren telemetria confiable en zonas remotas.": "Precision agriculture, environmental monitoring, renewable energies and academic initiatives that require reliable telemetry in remote areas.",
    "Flujo de logs en tiempo real via WebSocket.": "Real-time log stream via WebSocket.",
    "Conectado": "Connected",
    "Conectando...": "Connecting...",
    "Desconectado": "Disconnected",
    "Auto-scroll": "Auto-scroll",
    "Limpiar": "Clear",
    "entradas": "entries",
    "Esperando logs...": "Waiting for logs...",
    "Sin conexion al servidor": "No server connection"
  },
  es: {
    "Features": "Características",
    "Solutions": "Soluciones",
    "Documentation": "Documentación",
    "Sign up": "Registrarse",
    "Industrial 4.0 Standard": "Estándar Industrial 4.0",
    "Visualize and Optimize": "Visualiza y Optimiza",
    "Your": "Tu",
    "Network": "Red",
    "Real-time monitoring and advanced diagnostics for industrial-scale LoRa networks.": "Monitoreo en tiempo real y diagnóstico avanzado para redes LoRa a escala industrial.",
    "Start Monitoring": "Comenzar Monitoreo",
    "Watch Demo": "Ver Demo",
    "Infinite Scalability": "Escalabilidad Infinita",
    "Support for thousands of nodes across vast areas without degradation.": "Soporte para miles de nodos en grandes áreas sin degradación.",
    "Real-time Data": "Datos en Tiempo Real",
    "Instant latency tracking and packet delivery metrics with sub-second updates.": "Seguimiento instantáneo de latencia y métricas de entrega de paquetes con actualizaciones sub-segundo.",
    "Historical Analysis": "Análisis Histórico",
    "Deep trend analysis to predict failures before they occur.": "Análisis profundo de tendencias para predecir fallos antes de que ocurran.",
    "Ready to optimize your network?": "¿Listo para optimizar tu red?",
    "Enter your work email to receive a customized implementation plan.": "Ingresa tu correo laboral para recibir un plan de implementación personalizado.",
    "Enter your work email": "Ingresa tu correo laboral",
    "Get Consulted": "Solicitar Asesoría",
    "Privacy Policy": "Política de Privacidad",
    "Terms of Service": "Términos del Servicio",
    "API Keys": "Claves API",
    "Change language": "Cambiar idioma",
    "Change theme": "Cambiar tema",
    "LogoutLabel": "Cerrar Sesión",
    "Welcome Back": "Bienvenido de nuevo",
    "Access your mesh network dashboard": "Accede al panel de tu red mesh",
    "Usuario": "Usuario",
    "Contrasena": "Contrasena",
    "Sign In": "Iniciar sesion",
    "Ingresando...": "Ingresando...",
    "Credenciales invalidas": "Credenciales invalidas",
    "Error al conectar con la API": "Error al conectar con la API",
    "Industrial Mesh Control": "Control de Malla Industrial",
    "Real-time monitoring and deployment of LoRa-based sensor nodes.": "Monitoreo en tiempo real y despliegue de nodos sensores basados en LoRa.",
    "Active Network Nodes": "Nodos de Red Activos",
    "Provision New Node": "Aprovisionar Nuevo Nodo",
    "Edit Node Configuration": "Editar Configuración del Nodo",
    "Node Model": "Modelo del Nodo",
    "Refresh Rate (seconds)": "Tasa de Refresco (segundos)",
    "Deploy Node to Mesh": "Desplegar Nodo en la Malla",
    "Save Changes": "Guardar Cambios",
    "Cancel": "Cancelar",
    "Editar": "Editar",
    "Eliminar": "Eliminar",
    "Desactivar": "Desactivar",
    "Activar": "Activar",
    "Confirmar Eliminación": "Confirmar Eliminación",
    "Sí, Eliminar": "Sí, Eliminar",
    "Live Node Grid": "Cuadrícula de Nodos en Vivo",
    "Real-time telemetry from mesh nodes": "Telemetría en tiempo real de nodos de malla",
    "New Node": "Nuevo Nodo",
    "Offline": "Inactivo",
    "Active": "Activo",
    "nodos": "nodos",
    "Refresh": "Refresco",
    "Status": "Estado",
    "Actions": "Acciones",
    "Creando...": "Creando...",
    "Guardando...": "Guardando...",
    "No hay nodos disponibles.": "No hay nodos disponibles.",
    "Cargando nodos...": "Cargando nodos...",
    "Error al cargar los datos": "Error al cargar los datos",
    "Inicio": "Inicio",
    "Dashboard": "Panel Principal",
    "Panel de nodos": "Panel de nodos",
    "Informacion general de nodos": "Informacion general de nodos",
    "Gestor de nodos": "Gestor de nodos",
    "Panel de Nodos": "Panel de Nodos",
    "Mapa en Vivo": "Mapa en Vivo",
    "Históricos": "Históricos",
    "Log de Paquetes": "Log de Paquetes",
    "Buscar nodos, IPs...": "Buscar nodos, IPs...",
    "Configuración": "Configuración",
    "Cerrar Sesión": "Cerrar Sesión",
    "Nosotros": "Nosotros",
    "Descargas": "Descargas",
    "Proyecto": "Proyecto",
    "Ver panel": "Ver panel",
    "Ingresar": "Ingresar",
    "Ir al sistema": "Ir al sistema",
    "Nuestra Misión": "Nuestra Misión",
    "Equipo de Desarrollo": "Equipo de Desarrollo",
    "Desarrolladores del proyecto Final de Ingeniería Electrónica": "Desarrolladores del proyecto Final de Ingeniería Electrónica",
    "Firmware Nodos": "Firmware Nodos",
    "Gateway LoRa": "Gateway LoRa",
    "Guía de Instalación": "Guía de Instalación",
    "Recursos del Proyecto": "Recursos del Proyecto",
    "Repositorios oficiales y guías de configuración.": "Repositorios oficiales y guías de configuración.",
    "Bajo Consumo": "Bajo Consumo",
    "Optimizado para funcionar meses con baterias.": "Optimizado para funcionar meses con baterias.",
    "Largo Alcance": "Largo Alcance",
    "Comunicación de hasta 10km en línea de vista.": "Comunicación de hasta 10km en línea de vista.",
    "Seguridad": "Seguridad",
    "Cifrado AES-128 de extremo a extremo": "Cifrado AES-128 de extremo a extremo",
    "Red de sensores inalámbricos": "Red de sensores inalámbricos",
    "Sistema autónomo de monitoreo ambiental": "Sistema autónomo de monitoreo ambiental",
    "Resumen tecnico": "Resumen técnico",
    "¿Qué es LoRa Mesh?": "¿Qué es LoRa Mesh?",
    "Es una arquitectura de red donde los nodos cooperan": "Es una arquitectura de red donde los nodos cooperan",
    "Empoderando la telemetría industrial": "Empoderando la telemetría industrial",
    "Soluciones robustas para ambientes desafiantes.": "Soluciones robustas para ambientes desafiantes.",
    "Contacto": "Contacto",
    "Soporte": "Soporte",
    "Descargas y Recursos": "Descargas y Recursos",
    "Accede a los repositorios y guías de instalación del ecosistema LoRa Mesh.": "Accede a los repositorios y guías de instalación del ecosistema LoRa Mesh.",
    "Ir al Repositorio": "Ir al Repositorio",
    "Leer Guía": "Leer Guía",
    "Código fuente para los nodos LoRa Mesh basados en microcontroladores ESP32/Arduino.": "Código fuente para los nodos LoRa Mesh basados en microcontroladores ESP32/Arduino.",
    "Software para el nodo concentrador encargado de la recepción y envío de datos a la nube.": "Software para el nodo concentrador encargado de la recepción y envío de datos a la nube.",
    "Documentación paso a paso para desplegar tu propia red de monitoreo.": "Documentación paso a paso para desplegar tu propia red de monitoreo.",
    "Documentación técnica detallada para el despliegue de la red y configuración del software.": "Documentación técnica detallada para el despliegue de la red y configuración del software.",
    "Desarrollador y diseñador del sistema de telemetría LoRa Mesh. Enfocado en el hardware y la arquitectura de la red.": "Desarrollador y diseñador del sistema de telemetría LoRa Mesh. Enfocado en el hardware y la arquitectura de la red.",
    "Especialista en desarrollo web y despliegue del software. Encargado de la visualización y análisis de datos en tiempo real.": "Especialista en desarrollo web y despliegue del software. Encargado de la visualización y análisis de datos en tiempo real.",
    "Proyecto Final - Ingenieria Electronica": "Proyecto Final - Ingeniería Electrónica",
    "Monitoreo distribuido": "Monitoreo distribuido",
    "en": "en",
    "Plataforma orientada a zonas remotas que combina bajo consumo, alcance extendido y comunicacion multisalto para transportar lecturas ambientales hacia un nodo concentrador.": "Plataforma orientada a zonas remotas que combina bajo consumo, alcance extendido y comunicación multisalto para transportar lecturas ambientales hacia un nodo concentrador.",
    "Objetivo general": "Objetivo general",
    "Objetivo tecnico": "Objetivo técnico",
    "Objetivo de impacto": "Objetivo de impacto",
    "Implementar una red LoRa Mesh funcional para monitoreo en entornos sin infraestructura tradicional.": "Implementar una red LoRa Mesh funcional para monitoreo en entornos sin infraestructura tradicional.",
    "Validar comunicaciones multisalto entre nodos y concentrar datos en gateway para visualizacion web.": "Validar comunicaciones multisalto entre nodos y concentrar datos en gateway para visualización web.",
    "Ofrecer una alternativa replicable, de bajo costo operativo y adaptable a distintos escenarios.": "Ofrecer una alternativa replicable, de bajo costo operativo y adaptable a distintos escenarios.",
    "Nodos distribuidos": "Nodos distribuidos",
    "Comunicacion Mesh": "Comunicación Mesh",
    "Gateway + plataforma": "Gateway + plataforma",
    "Captura de variables ambientales en diferentes puntos de campo.": "Captura de variables ambientales en diferentes puntos de campo.",
    "Los datos se enrutan por saltos intermedios para extender cobertura y mejorar resiliencia.": "Los datos se enrutan por saltos intermedios para extender cobertura y mejorar resiliencia.",
    "Centralizacion de datos y visualizacion historica en una interfaz web simple.": "Centralización de datos y visualización histórica en una interfaz web simple.",
    "Aplicaciones potenciales": "Aplicaciones potenciales",
    "Agricultura de precision, monitoreo ambiental, energias renovables e iniciativas academicas que requieren telemetria confiable en zonas remotas.": "Agricultura de precisión, monitoreo ambiental, energías renovables e iniciativas académicas que requieren telemetría confiable en zonas remotas.",
    "Integrante 1": "Integrante 1",
    "Integrante 2": "Integrante 2",
    "Documentación técnica detallada para el despliegue de la red y configuración del software.": "Documentación técnica detallada para el despliegue de la red y configuración del software."
  }
};

const ThemeLangContext = createContext();

export function ThemeLangProvider({ children }) {
  const [theme, setTheme] = useState(() => localStorage.getItem('theme') || 'dark');
  const [language, setLanguage] = useState(() => localStorage.getItem('language') || 'es');

  useEffect(() => {
    localStorage.setItem('theme', theme);
    document.documentElement.setAttribute('data-theme', theme);
  }, [theme]);

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.setAttribute('lang', language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  const toggleTheme = () => setTheme(prev => prev === 'dark' ? 'light' : 'dark');
  const changeLanguage = (lang) => setLanguage(lang);

  return (
    <ThemeLangContext.Provider value={{ theme, toggleTheme, language, changeLanguage, t }}>
      {children}
    </ThemeLangContext.Provider>
  );
}

export function useThemeLang() {
  return useContext(ThemeLangContext);
}
